version: '3.7'
services:
  db:
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27117:27017'
  app_repository:
    build: .
    image: node
    container_name: app_repository
    env_file: '.env'
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - '.:/home/node/api_repository'
      - '/home/node/api_repository/node_modules'
    command: 'npm run start:dev'
    depends_on:
      - db
    links:
      - db
